name: Update documentation
on:
  push:
    branches:
      - dev 
jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
        - uses: actions/checkout@v3
          with:
              ref: dev
              fetch-depth: 0
        - uses: ammaraskar/sphinx-action@master
          with:
              build-command: "sphinx-build -b html . _build"
              docs-folder: "docs/source"
        - name: Commit documentation changes
          run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add .
              git commit -m "Update documentation" -a || true
              # The above command will fail if no changes were present, so we ignore
              # that.
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            branch: dev
            github_token: ${{ secrets.GITHUB_TOKEN }}
