on:
  release:
    types: [released]
  workflow_dispatch: ~

name: Release
env:
  CACHE_VERSION: 2
  DEFAULT_PYTHON: 3.8
jobs:
  update_docs:
    permissions: write-all
    uses: AleksandrShvarts/dummy/blob/dev/.github/workflows/docs.yml@v1

